# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/debcvescan/main.go
  goos:
    - linux

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

nfpms:  
  - id: debcvescan
    package_name: debcvescan
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
    - debcvescan    

    replacements:      
      386: i386

    vendor: Devmatic IT
    homepage: https://github.com/devmatic-it/debcvescan
    maintainer: F. Bator <bator@devmatic-it.com>
    description: CVE Security Scanner for Debian Linux distributions using official Debian Security Bug Tracker <https://security-tracker.debian.org/tracker>.
    license: Apache 2.0

    # Formats to be generated.
    formats:
      - deb
      
    bindir: /usr/bin
