name: DebianRepository
on: [push]

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Validates GO releaser config
        uses: docker://goreleaser/goreleaser:latest
        with:
          args: check

      - name: Create release on GitHub
        uses: docker://goreleaser/goreleaser:latest
        with:
          args: release --snapshot
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Debian repository test
        uses: devmatic-it/debrepo-action@v1
        with:
          who-to-greet: 'hello world'
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
