name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.19
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build
      run: make

    - name: Update coverage.txt
      uses: test-room-7/action-update-file@v1
      with:
          file-path: coverage.txt
          commit-msg: Update coverage file for sonarcloud.io
          github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: codecov upload     
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required
        file: ./coverage.txt
